server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/task-manager"
    username: "postgres"
    password: "02062004"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "xdk5CbTZYC/3i7k+OhKjvXGadGvjKmDlgnsz4leEm1hsXp3XamwxlSTcikfKJhXG"

admin:
  password: "admin"

