server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/task-manager"
    username: "root"
    password: "Quang7204@"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "xdk5CbTZYC/3i7k+OhKjvXGadGvjKmDlgnsz4leEm1hsXp3XamwxlSTcikfKJhXG"

admin:
  password: "admin"

