server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/task-manager"
    username: "root"
    password: "Quang7204@"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true